"use client";

import "@/app/globals.css";
import Navbar from "./Navbar/page";
import Footer from "./components/Footer";
import { Toaster } from "react-hot-toast";
import { SessionProvider } from "next-auth/react";

// export const metadata = {
//   title: "Fast food",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta charSet="UTF-8" />
        <meta name="robots" content="index, follow" />

        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Ruthie&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="bg-gray-200 min-h-screen text-black">
        <SessionProvider>
          <Navbar />
          <Toaster />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
